Return errors from TSA verification if there are no valid timestamps
sigstore/sigstore-go pull request #325
Opened 2024-10-29 16:23 UTC by codysoyland

#### Summary

#### Release Note

#### Documentation

2024-10-29 16:31 UTC, codysoyland commented
There is still a test failure here, as the test expects that there is no returned error even if there are no valid timestamps (as the count of timestamps is used to test against the threshold, which may be zero). Should we update that test? Or is there a valid reason to expect that behavior?

2024-10-29 17:38 UTC, phillmv commented
>as the test expects that there is no returned error even if there are no valid timestamps (as the count of timestamps is used to test against the threshold, which may be zero). Should we update that test? Or is there a valid reason to expect that behavior?

Thinking out loud, should `VerifyTimestampAuthority` error if there are no entity.Timestamps() to verify?

On the one hand, I'm inclined to say "yes". It feels dangerous to be have a function named "Verify" that can return successfully _when it has not actually verified anything_. This got us in trouble in `gh at verify` recently, where we returned successfully when supplied with an empty list of attestations.

On the other hand, as currently implemented there is some ambiguity around how `VerifyObserverTimestamps` calls this function; as currently implemented, returning a zero-len array is expected behaviour. **However** I'm not a huge fan of how `VerifyObserverTimestamps` ended up & would be willing to endorse a polite refactor - do we remember why the `TlogInclusion` is verified independently of this function?

2024-10-29 17:57 UTC, haydentherapper requested changes
This was set up intentionally to support verification with multiple timestamp sources. `VerifyTimestampAuthorityWithThreshold` requires a threshold, while `VerifyTimestampAuthority` does not. `VerifyTimestampAuthority` must be used with another function that will implement a threshold, which is done [here](https://github.com/sigstore/sigstore-go/blob/main/pkg/verify/signed_entity.go#L715-L720).

If we add a baseline threshold check to `VerifyTimestampAuthority`, then verification would fail if both TSA timestamps and SETs are provided where the trust root only specifies verification material for SETs.

2025-05-07 19:39 UTC, codysoyland commented on pkg/verify/tsa.go
> +	return verifiedTimestamps, err
This is a bit unconventional, as an error value may be returned even if there was a successful verification. Callers should check the returned `verifiedTimestamps` even if there were errors. The errors are only populated if there was at least one failed verification.

2025-05-07 21:41 UTC, codysoyland commented on pkg/verify/tsa.go
> +	return verifiedTimestamps, err
Thinking about this more, we can distinguish between verification errors and other types of errors by changing the return values of `func VerifyTimestampAuthority`:
```go
func VerifyTimestampAuthority(...) ([]*root.Timestamp, error)
```
to:
```go
func VerifyTimestampAuthority(...) ([]*root.Timestamp, []error, error)
```
where the added `[]error` would represent verification errors.

This would require a public API change but would read more like conventional Go code, where a non-nil error usually means a total failure.

2025-05-08 12:43 UTC, steiza approved these changes
LGTM!

2025-05-08 12:44 UTC, steiza commented
Sorry, I thought I was on #472

2025-05-08 19:00 UTC, haydentherapper commented on pkg/verify/tsa.go
> +	return verifiedTimestamps, err
Like you mentioned, this is non conventional for Go. I'm partial to what you proposed in 473.

2025-05-08 19:02 UTC, codysoyland commented
Closing in favor of https://github.com/sigstore/sigstore-go/pull/473

2025-05-08 19:02 UTC, closed without merging